### ISSUE TITLE
code blocks should scroll horizontally if they exceed the content width

### ISSUE THREAD

**Issue by craftyguy** [pawroman/zola-theme-terminimal#12]
Code blocks with long lines cause the entire page to overflow/scroll horizontally, which looks really bad:

![2022-01-27-144708_grim](https://user-images.githubusercontent.com/1474209/151455984-aac3936a-2cd5-4eb7-a65f-c65a9b27f599.png)

This is what I'd expect to happen in these situations:

![2022-01-27-144449_grim](https://user-images.githubusercontent.com/1474209/151455869-3e0b825e-216c-4ef1-87d4-a87cc342ec8a.png)

I couldnt' get this to work by setting `overflow-x:scroll` in the `pre` CSS, but I did get it to work when I wrapped the `<pre>` in a `<div style="overflow-x:scroll">`

**Comment by Vloupmon** [comment]
I found the same problem *on the index* : code block text takes up the full width. But it doesn't do so on specific pages. From what I can tell, it actually comes from `.posts` overflowing `.content` on the index. Once you add `width: 100%` it behaves normally. The code blocks themselves are on `overflow: auto` and will adapt to the width they have available.

Default CSS :
![image](https://user-images.githubusercontent.com/6957532/161270097-c293d29a-7956-460b-983b-9fec714aeba1.png)

Code block overflowing:
![image](https://user-images.githubusercontent.com/6957532/161270729-c5f192c9-3f85-4ae7-b740-bf96aba70f67.png)

With the same CSS values as on individual pages :
![image](https://user-images.githubusercontent.com/6957532/161270438-5801f06c-2a59-47d4-95e5-b512ebedc326.png)

Code block behaving properly:
![image](https://user-images.githubusercontent.com/6957532/161270968-75211f8f-ea91-407b-bc57-b6d84bd45e4e.png)

**Comment by pawroman** [comment]
Hi, I'm really happy to see other people using the theme. Thanks for the detailed investigation, write-up and the PR!

**Comment by pawroman** [comment]
The fix has been merged. Thanks!
