### ISSUE TITLE
Post view navigation broken in zola 0.16

### ISSUE THREAD

**Issue by ruscur** [pawroman/zola-theme-terminimal#20]
The post view navigation HTML isn't injected into posts in zola 0.16, but it works with the same config in 0.15.3.

I haven't bisected zola yet but it should be pretty easy to find.  I'm also not sure if this is a theme regression or a potential zola regression.

**Comment by apisashla** [comment]
Also having this issue. If I figure out why, I'll put it here. Darnedest thing.

**Comment by pawroman** [comment]
I found the reason for it being broken. The wording of `page.earlier` and `page.later` has changed to `page.lower` and `page.higher`. https://www.getzola.org/documentation/content/section/#date

I will merge a fix soon.
