### ISSUE TITLE
add support for extra.stylesheets

### ISSUE THREAD

**Issue by hsn10** [pawroman/zola-theme-terminimal#28]
See this: https://www.getzola.org/themes/apollo/

Its needed for easier site CSS customisation.

**Comment by pawroman** [comment]
Hey, good idea. I would gladly accept a contribution, since I don't have the time to add it myself :smile:

**Comment by hsn10** [comment]
I _do not believe_ you. You have unprocessed pull requests. Why should I believe that you will handle mine?

**Comment by pawroman** [comment]
@hsn10 The offer still stands, as you might see, I have merged quite a few PRs since your comment :smile:
