### ISSUE TITLE
Add website source as a footer setting

### ISSUE THREAD

**Issue by tranzystorek-io** [pawroman/zola-theme-terminimal#29]
I'd like to add a link to the source repo of the website; the footer seems like the perfect place. This could be implemented as a `config.extra.website_source` setting that would add sth like "This website is <link>open-source</link>".

**Comment by pawroman** [comment]
Hey, I think this kind of stuff is best realized by inheriting the `index` template and using the `footer` block with a `super()` call, like so:

```jinja
{% extends "terminimal/templates/index.html" %}

{% block footer %}
    {{ super() }}
    <!-- your extra HTML code goes here, or above super() -->
{% endblock footer %}
```

More info on this:

- https://www.getzola.org/documentation/themes/installing-and-using-themes/
- https://tera.netlify.app/docs/#inheritance

I think it should do the trick for you, but if it's not enough then maybe the theme could gain a new block.

**Comment by tranzystorek-io** [comment]
Ah yeah, forgot about inheriting, that will do the trick nicely, thanks!

**Comment by tranzystorek-io** [comment]
One caveat is that without some adjustment like an `extra_footer` block, another copyright/copyright-theme block needs to be started to get the theming and looks a bit uglier:

![obraz](https://user-images.githubusercontent.com/5671049/226574354-71ce17c9-f05f-4ab6-9d36-d6fd3366babd.png)

**Comment by pawroman** [comment]
That looks like something you could attempt to solve with some custom CSS. But hey, if you really need the `extra_footer`, please feel free to contribute it!

**Comment by tranzystorek-io** [comment]
> if you really need the `extra_footer`

that's never an easy question 😅
