### ISSUE TITLE
Add option to use Open Graph (for better link previews in messaging apps / social media)

### ISSUE THREAD

**Issue by pawroman** [pawroman/zola-theme-terminimal#3]
Currently, the theme doesn't use Open Graph: https://ogp.me/

The theme should have an option to use Open Graph, to generate properties like `title`, `url` and `description` automatically.

This would allow to show better link previews when pasting links to apps like Slack etc.

**Comment by heitorPB** [comment]
I'd like to work on this task.

`title`, `type`, and `url` seems straightforward to have for all pages (home page, archive, posts).

But what about `description`? Should it be the the `page.description` from the frontmatter if set?

Another thing I'd like to have is the `og:image`. My idea for this one is to have a global option in the `config.toml` with a `open_graph_default_image` for all pages, and a possibility to overwrite it in the posts' frontmatter.

What do you think @pawroman?

**Comment by AntoniosBarotsis** [comment]
The image could also default to the favicon, I think that's what the original Hugo theme did. How is this coming along by the way? Wouldn't mind helping if the author is still active :)

**Comment by jh-devv** [comment]
> Wouldn't mind helping if needed :)

Same!

**Comment by heitorPB** [comment]
I finally finished it :tada: At least I think so. Can you guys check-out/test my branch https://github.com/heitorPB/zola-theme-terminimal/tree/opengraph? That should add OpenGraph tags everywhere (and also fix Markdown in figures' captions as a bonus - see #51).
