### ISSUE TITLE
How do I get the archive to generate?

### ISSUE THREAD

**Issue by 0xDEADFED5** [pawroman/zola-theme-terminimal#30]
Thanks for the awesome theme!  I've got tags working, what's the secret to getting the archive to build?

**Comment by pawroman** [comment]
Hey, make sure you have the `tags` taxonomy set up.

Example:
```
taxonomies = [
    {name = "tags", sort_by = "date"}
]
```

Also check out [`config.toml`](https://github.com/pawroman/zola-theme-terminimal/blob/master/config.toml) and [`content`](https://github.com/pawroman/zola-theme-terminimal/tree/master/content) directory of the repo, the example site deployed at https://pawroman.github.io/zola-theme-terminimal/ is built from these.

**Comment by 0xDEADFED5** [comment]
damn, that was too easy.  thanks for the help
