### ISSUE TITLE
Bug: image shortcodes work in `zola serve` but not `zola build`

### ISSUE THREAD

**Issue by goingforbrooke** [pawroman/zola-theme-terminimal#36]
### Issue

When you add an image with Terminimal's [image shortcode](https://github.com/pawroman/zola-theme-terminimal/tree/master#image), it's visible locally (via `zola serve`) but not on GitHub Pages, where it's built via `zola build` in [`zola-deploy-action`](https://github.com/shalzz/zola-deploy-action).

### Misc.

I'm using the master branch of [`zola-deploy-action`](https://github.com/shalzz/zola-deploy-action) due to a [breaking bug](https://github.com/shalzz/zola-deploy-action/issues/71#issuecomment-1501488817).

**Comment by pawroman** [comment]
Fixed in #37
