### ISSUE TITLE
Variable 'config.extra.page_titles' not found in context while rendering 'macros/title.html'

### ISSUE THREAD

**Issue by djanda97** [pawroman/zola-theme-terminimal#44]
Hello,

I'm interested in using this theme for my blog but I ran into an issue during setup. I successfully added the theme via the `git submodule add https://github.com/pawroman/zola-theme-terminimal.git themes/terminimal` command and added the `theme = "terminimal"` value to my `config.toml` file. The issue that I encountered occurred when trying to run `zola serve`:

![image](https://github.com/pawroman/zola-theme-terminimal/assets/8923819/cd12205e-d32b-412c-8ad5-84a97e982d17)

For reference, this is the content of the `content/_index.md` file, showing that the `template` and `page_template` values are set to their respective files under the `terminimal/templates/` directory:

![image](https://github.com/pawroman/zola-theme-terminimal/assets/8923819/0f3fae8d-8ef2-4ac3-a8ae-be33432832a8)

In the `themes/terminimal/config.toml` file there is a default value for the `page_titles` variable, however it seems that it is not being recognized. I found a workaround in order for the site to be successfully served by setting `page_titles = "combined"` under the `[extra]` section in my `config.toml` file, but I'm not sure if it is the indented behavior for a user to be required to set this value.

Thanks,
David

**Comment by djanda97** [comment]
Reading the [templates/macros/title.html](https://github.com/pawroman/zola-theme-terminimal/blob/master/templates/macros/title.html) file, shouldn't the title fallback to `{{ main_title }}` if a user hasn't set a value for `config.extra.page_titles` instead of failing to build?

**Comment by djanda97** [comment]
Using Zola version 0.17.2

**Comment by pawroman** [comment]
Hey, yes, absolutely right. This config entry shouldn't be required, and the theme should fallback to `{{ main_title }}`.

Looks like this is easily fixed by changing the way the title macro accesses this config entry. Something like this seems to do the trick:

```diff
-{%- if config.extra.page_titles and config.extra.page_titles == "combined" -%}
+{%- if config.extra.page_titles == "combined" -%}

...

-{%- elif config.extra.page_titles == "page_only" -%}
+{%- elif config.extra.page_titles and config.extra.page_titles == "page_only" -%}
```

Would you be OK with contributing this fix in a pull request? I'd be happy to merge it.

**Comment by djanda97** [comment]
Gladly! I'll open a PR with the suggested fix :smile:
