### ISSUE TITLE
Support ATOM feeds

### ISSUE THREAD

**Issue by heitorPB** [pawroman/zola-theme-terminimal#48]
Currently, the theme hardcodes the path to the RSS feed (if it exists), which can be an issue if you use ATOM instead.

RSS feeds are usually named `rss.xml` while ATOM ones are `atom.xml`, but could be anything else.

I have a backwards-compatible change to `template/index.html` that works for both types of feed in #35, is this something that the project is interested in?

**Comment by pawroman** [comment]
Related to #71
