### ISSUE TITLE
Top margin for sub lists seems off

### ISSUE THREAD

**Issue by WaffleLapkin** [pawroman/zola-theme-terminimal#5]
![image](https://user-images.githubusercontent.com/38225716/129458192-d0e9199f-784d-4b6d-b198-b780da184746.png)

It seems that there shouldn't be margin at all, but there is and it's pretty big (20 px)

**Comment by pawroman** [comment]
Thanks for reporting the issue!

I don't currently have the time to work on this theme much, so either feel free to submit a PR, or please patiently wait for me to find some time to look into it :wink:
