### ISSUE TITLE
Is it possible to add like more text to the index page?

### ISSUE THREAD

**Issue by jh-devv** [pawroman/zola-theme-terminimal#55]
Maybe like someway to tag a blog to always show as the latest?

**Comment by jh-devv** [comment]
![Screenshot_20230901_131435](https://github.com/pawroman/zola-theme-terminimal/assets/122896463/585d5a60-26af-4a85-9641-cf493793c6c8)
Basically maybe something like this?

**Comment by pawroman** [comment]
Hmm, I'm not sure if having a "pinned" post would be the best solution here.

A simple solution that doesn't need any extra development for the theme itself: you could inherit the theme's `index.html` template and override the `content` block, to add some extra content before all the posts, followed by `super()` to render the "base" content block.

See Zola's docs for some hints on this https://www.getzola.org/documentation/themes/extending-a-theme/

And also see Tera docs (the template engine that Zola uses) https://keats.github.io/tera/docs/#child-template

**Comment by heitorPB** [comment]
I created a new template for my landing page: [heitorpb.github.com](https://heitorpb.github.com). Then I created a `content/_index.md` that uses that template.

**Comment by pawroman** [comment]
@jh-devv Does the above solve it for you?

**Comment by jh-devv** [comment]
> @jh-devv Does the above solve it for you?

Yea, thanks very much!
