### ISSUE TITLE
Unsure how to use this theme

### ISSUE THREAD

**Issue by ddejohn** [pawroman/zola-theme-terminimal#70]
I've set up a new blog with Zola, and added this theme. I went through the initial setup with Zola (creating templates, and a first blog post), but this theme does not seem to work when previewing the site locally. It's not clear from Terminimal's or Zola's docs what is required in the templates folder at the root of the project, if anything.

What am I missing?

Thanks

**Comment by heitorPB** [comment]
You don't need to add anything in the `templates/` directory. You clone this theme into the `themes/` dir and modify `config.toml` to use the theme.

See https://www.getzola.org/documentation/themes/installing-and-using-themes/ for details.

**Comment by pawroman** [comment]
Closing as non-issue. Please reopen if it's specific to the theme somehow.

**Comment by ddejohn** [comment]
> You don't need to add anything in the `templates/` directory. You clone this theme into the `themes/` dir and modify `config.toml` to use the theme.
> 
> See https://www.getzola.org/documentation/themes/installing-and-using-themes/ for details.

I've done exactly this but my blog is completely blank when running it locally. I suppose I'll try from scratch tomorrow.
