### ISSUE TITLE
tags not working

### ISSUE THREAD

**Issue by ddejohn** [pawroman/zola-theme-terminimal#74]
I am trying to enable tags on my blog. I have not moved any of my content over from my old blog so I'm just using the pages included in the Terminimal demo. Following [the docs](https://github.com/pawroman/zola-theme-terminimal/tree/master?tab=readme-ov-file#tags), I have this in my config:

```toml
# config.toml

[extra]
taxonomies = [{ name = "tags" }]
```

But when attempting to `serve` or `build` the site, zola reports this error:

```bash
$ zola serve --open
Building site...
Error: Failed to serve the site
Error: Page `/path/to/blog/content/welcome-terminimal-theme.md` has taxonomy `tags` which is not defined in config.toml
```

**Comment by heitorPB** [comment]
It shouldn't be in `[extra]`, you define the taxonomies in the top level part, before any `[]`.
